// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlTTEvEuRNfsXdRSLtJ2kApbE1_vnDVvk',
    appId: '1:750284049626:android:951f5f5999b431128ce9e3',
    messagingSenderId: '750284049626',
    projectId: 'bananizeapp',
    storageBucket: 'bananizeapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-3bpOwXc-lnm3i-nm6Vyk_GFqEyETeOc',
    appId: '1:750284049626:ios:d104b5a28b3b8d7a8ce9e3',
    messagingSenderId: '750284049626',
    projectId: 'bananizeapp',
    storageBucket: 'bananizeapp.firebasestorage.app',
    iosBundleId: 'com.example.bananizeMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-3bpOwXc-lnm3i-nm6Vyk_GFqEyETeOc',
    appId: '1:750284049626:ios:d104b5a28b3b8d7a8ce9e3',
    messagingSenderId: '750284049626',
    projectId: 'bananizeapp',
    storageBucket: 'bananizeapp.firebasestorage.app',
    iosBundleId: 'com.example.bananizeMobileApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV8O9KH5D1V2nS2j0NpNx9f9G9JvNzfts',
    appId: '1:750284049626:web:69ebea4a3fa495738ce9e3',
    messagingSenderId: '750284049626',
    projectId: 'bananizeapp',
    authDomain: 'bananizeapp.firebaseapp.com',
    storageBucket: 'bananizeapp.firebasestorage.app',
    measurementId: 'G-HHKCM5YTYR',
  );
}
