name: bananize_mobile_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  firebase_auth:
  google_sign_in:
  http: ^1.2.2

dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: lib/Assets/Fonts/Roboto-Black.ttf
        - asset: lib/Assets/Fonts/Roboto-Italic.ttf
        - asset: lib/Assets/Fonts/Roboto-Light.ttf
        - asset: lib/Assets/Fonts/Roboto-Medium.ttf
        - asset: lib/Assets/Fonts/Roboto-Regular.ttf
        - asset: lib/Assets/Fonts/Roboto-Thin.ttf
        - asset: lib/Assets/Fonts/Roboto-Bold.ttf
          weight: 700
  assets:
    - lib/Assets/Images/banana-white.png
    - lib/Assets/Images/banana-black.png
    - lib/Assets/Images/1657952440google-logo-png-transparent.png.webp
    - lib/Assets/Images/Facebook_Logo_2023.png
    - lib/Assets/Images/976px-Apple_logo_black.svg.png

flutter_icons:
  android: true
  ios: true
  image_path: "lib/Assets/Images/banana-white.png"
